disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - file_length
  - type_body_length
  - cyclomatic_complexity
  - force_cast
  - force_try
  - force_unwrapping

opt_in_rules:
  - empty_count
  - missing_docs
  - force_unwrapping

included:
  - fungame iOS
  - fungame Shared
  - fungame macOS
  - fungame tvOS

excluded:
  - Pods
  - fungameTests
  - fungameUITests

line_length:
  warning: 120
  error: 200

type_name:
  min_length: 3
  max_length: 40

identifier_name:
  min_length: 2
  max_length: 40

function_body_length:
  warning: 50
  error: 100

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 10
  error: 20 